# -*- coding: utf-8 -*-
"""candidate_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LdCoxEUJHtYr_V2ocTr6O7lTsow9m6-3
"""

candidate = {

    "name": "Saurav Mitra",

    "skills": [
        "Python",
        "SQL",
        "Power BI",
        "Excel",
        "Data Visualization"
    ],

    "experience": 2,

    "achievement_score": 9,

    "education_score": 8.5
}