# -*- coding: utf-8 -*-
"""explainability.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LdCoxEUJHtYr_V2ocTr6O7lTsow9m6-3
"""

def generate_explanation(score):

    if score >= 8:
        recommendation = "Highly Recommended"

    elif score >= 6:
        recommendation = "Recommended"

    else:
        recommendation = "Low Match"

    return recommendation