# -*- coding: utf-8 -*-
"""feature_engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LdCoxEUJHtYr_V2ocTr6O7lTsow9m6-3
"""

def calculate_skill_score(candidate_skills, jd_skills):
    """
    Calculate skill matching score
    """

    matched_skills = set(candidate_skills).intersection(set(jd_skills))

    score = len(matched_skills) / len(jd_skills)

    return round(score * 10, 2)