# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LdCoxEUJHtYr_V2ocTr6O7lTsow9m6-3
"""

import pandas as pd


def preprocess_data(df):
    """
    Clean candidate data
    """
    df = df.drop_duplicates()
    df = df.fillna("")

    return df

pip install requests