# -*- coding: utf-8 -*-
"""ranking_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LdCoxEUJHtYr_V2ocTr6O7lTsow9m6-3
"""

def calculate_final_score(
        skill_score,
        experience_score,
        achievement_score,
        education_score):

    final_score = (
        0.40 * skill_score
        + 0.30 * experience_score
        + 0.20 * achievement_score
        + 0.10 * education_score
    )

    return round(final_score, 2)