# -*- coding: utf-8 -*-
"""similarity_search.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LdCoxEUJHtYr_V2ocTr6O7lTsow9m6-3
"""

from sklearn.metrics.pairwise import cosine_similarity
import numpy as np


def calculate_similarity(candidate_vector,
                         jd_vector):

    similarity = cosine_similarity(
        [candidate_vector],
        [jd_vector]
    )

    return similarity[0][0]